#!/bin/bash
set -eu -o pipefail

data="$1"
shift 1
prefix="${data%%.data}"

n=$(sed 's#.*_0*\([0-9]\+\)\.data#\1#' <<< "$data")


function gpl_gen
{
  local title=$1
  local ox=$2
  local oy=$3
  local data_pos=$4
  local color=\"$5\"
  local surfix=$6
  local style=$7
  shift 7
  opts=()
  if [ "$style" = "lines" ]
  then
    opts+=(lw 3)
    opts+=(lc rgb "$color")
  fi
  {
    cat <<EOF
set terminal svg

set title  "$title" font "Times,20"
set xlabel "$ox"  font "Times,16"
set ylabel "$oy" font "Times,16

set xrange [0:2500]
set yrange [0:]

unset key

plot "$data" using 1:$data_pos with $style ${opts[@]}
EOF
  } > "${prefix}_$surfix.gpl"

  gnuplot "${prefix}_$surfix.gpl" > "${prefix}_$surfix.svg"
}


gpl_gen "samples per iteration" "iterations" "samples" 2 "orange" "samples" "lines"
gpl_gen "integral of samples per iteration" "iterations" "integral of samples" 3 "blue" "samples_int" "lines"
gpl_gen "total price per player" "iterations" "total price per player" 4 "red" "total_price_pp" "points"
gpl_gen "average cards count per player" "iterations" "average cards count per player" 5 "cyan" "avg_cards_pp" "points"
