#!/bin/bash
set -eux -o pipefail

time g++ -O3 -DNDEBUG sim.cpp -o sim.out

mkdir -p "out"

for players in {1..10}
do
  time ./sim.out "$players" 300 5 9.50 100000 > "out/players_${players}.csv"
done
