#!/bin/bash
set -eux -o pipefail

time g++ -O3 -DNDEBUG sim.cpp -o sim.out

mkdir -p "out"

for players in {1..10}
do
  n=$(printf '%02d' "$players")
  data="out/players_${n}.data"
  time ./sim.out "$players" 300 5 9.50 100000 > "$data"
  ./player_stats "$data"
done

./stats
